language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require fxp/composer-asset-plugin:~1.0
  - travis_retry composer install --prefer-dist --no-interaction --dev

before_script:
  - mysql -e 'create database yii2_multilingual;'
  - mysql yii2_multilingual < tests/migrations/mysql.sql

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml --verbose $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.0' ]; then
      cd ../../.. 
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    fi

cache:
  - vendor
  - $HOME/.composer/cache

after_success:
    - bash <(curl -s https://codecov.io/bash)